<!doctype html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <title>My portfolio</title>
    <link rel="stylesheet" href="assets/css/style.css" type="text/css">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" type="image/png" href="assets/img/portfolio-flaticon.png">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css" integrity="sha512-Kc323vGBEqzTmouAECnVceyQqyqdsSiqLQISBL29aUW4U/M7pSPA/gEUZQqv1cwx4OnYxTxve5UMg5GT6L4JJg==" crossorigin="anonymous" referrerpolicy="no-referrer">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">
</head>
<body>
    <header>
        <a href="index.php?route=home"><h1 title="Back home"><?= htmlspecialchars($user->getFirstname()) ?>'s portfolio</h1></a>
        <?php if(!isset($_SESSION['user'])): ?>
            <a href="index.php?route=login"><i class="fa-solid fa-lock"></i></a>
        <?php endif; ?>
        
        <?php if(isset($_SESSION['user'])): ?>
            <a href="index.php?route=dashboard">Back to the dashboard</a>
            <a href="index.php?route=logout" class="logout"><i class="fa-solid fa-arrow-right-from-bracket"></i></a>
        <?php endif; ?>
    </header>
    
    <main class="container">
        <?php require $template.'.phtml' ?>
    </main>
    
    <footer>
        <h3>by <?= htmlspecialchars($user->getFirstname()) ?></h3>
        <p>© katori.ovh. All rights reserved</p>
    </footer>
</body>
</html>