<!doctype html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <title>My portfolio</title>
    <link rel="stylesheet" href="assets/css/style.css" type="text/css">
    <link rel="shortcut icon" type="image/png" href="assets/img/portfolio-flaticon.png">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css" integrity="sha512-Kc323vGBEqzTmouAECnVceyQqyqdsSiqLQISBL29aUW4U/M7pSPA/gEUZQqv1cwx4OnYxTxve5UMg5GT6L4JJg==" crossorigin="anonymous" referrerpolicy="no-referrer">
</head>
<body>
    <header>
        <a href="index.php?route=home"><h1><?= htmlspecialchars($user->getFirstname()) ?>'s portfolio</h1></a>
        <a href="index.php?route=login"><i class="fa-solid fa-lock"></i></a>
    </header>
    
    <main class="container">
        <?php require $template.'.phtml' ?>
    </main>
    
    <footer>
        <h3>by <?= htmlspecialchars($user->getFirstname()) ?></h3>
        <p>© Ryenndev.com. All rights reserved</p>
    </footer>
</body>
</html>